name: Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Python wheel and publish to PyPI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: python -m pip install --upgrade pip build
    - name: Build
      run: python -m build --wheel
    - name: Upload whl file
      uses: actions/upload-artifact@v4
      with:
        name: whl
        path: dist/

  publish-to-pypi:
    name: PublishPyPI

    needs:
    - build

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/keycap-designer

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: whl
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
